### ISSUE TITLE
Could you explain if your bundle workable and how to set up it?

### ISSUE THREAD

**Issue by shtumi** [secotrust/SecotrustSabreDavBundle#1]
I need to integrate sabredav server to my Symfony 2 application in order to provide calDAV to our users. And i want to use your bundle.
But i faced with some problems during integration your bundle. Here is no documentation. But as i understand i need to define collection with tag secotrust.sabredav.collection. But how should looks this collection? Could you provide any example?

Thanks!

**Comment by snc** [comment]
Currently only WebDAV is supported, but I just added the needed CalDAV plugin configuration to the bundle.

As far as I understand reading the `calendarserver.php` of SabreDAV you need an implementation of `Sabre\DAVACL\PrincipalBackend\BackendInterface` and `Sabre\CalDAV\Backend\BackendInterface` in addition to an implementation of `Sabre\DAV\Auth\Backend\BackendInterface` where `Secotrust\Bundle\SabreDavBundle\SabreDav\AuthBackend` could be used.

You could try the following configuration:

```
secotrust_sabre_dav:
    base_uri: /app_dev.php/dav/
    plugins:
        acl: true
        auth: true
        browser: true
        caldav: true

services:
    caldav.principal.backend:
        class: My\PrincipalBackend
    caldav.calendar.backend:
        class: My\CalDAVBackend
    caldav.principal.collection:
        class: Sabre\CalDAV\Principal\Collection
        arguments:
            - @caldav.principal.backend
        tags:
            - { name: secotrust.sabredav.collection }
    caldav.calendarrootnode:
        class: Sabre\CalDAV\CalendarRootNode
        arguments:
            - @caldav.principal.backend
            - @caldav.calendar.backend
        tags:
            - { name: secotrust.sabredav.collection }
```

**Comment by shtumi** [comment]
Thank you a lot!
I finally integrated calDav to my project.
Could you also update your bundle version at packagist website?

**Comment by snc** [comment]
Well there is no concrete version at packagist, this bundle is not really in a stage where a version number makes sense. Using `"secotrust/sabredav-bundle": "1.0.*@dev"` will already fetch the latest version. Is this OK for you?

**Comment by databoy** [comment]
This looks very interesting. Have you considered adding the above example to the Docs?

**Comment by snc** [comment]
Definitely, time is the only problem currently ;-)

**Comment by databoy** [comment]
I'm about to give this a go... What configuration would you recommend for a basic WebDAV implementation in Symfony 2.4?

UPDATE: I was able to get it working (with only a rudimentary knowledge of how to put it all together), but I'd be grateful if you can provide an example configuration and a controller that shows how to integrate Gaufrette collections and Doctrine and while it's at it make coffee... :-)

**Comment by snc** [comment]
A sample config using the gaufrette local adapter:

``` yaml
secotrust_sabre_dav:
    base_uri: /app_dev.php/dav/
    plugins:
        browser: true

services:
    gaufrette.adapter:
        class: Gaufrette\Adapter\Local
        arguments:
            - "%kernel.root_dir%/../web/uploads"
    gaufrette.filesystem:
        class: Gaufrette\Filesystem
        arguments:
            - @gaufrette.adapter
    gaufrette.dav.collection:
        class: Secotrust\Bundle\SabreDavBundle\SabreDav\Gaufrette\Collection
        arguments:
            - @gaufrette.filesystem
        tags:
            - { name: secotrust.sabredav.collection }
```

I never created a doctrine implementation and I think that you will always need a custom implementation to create a directory tree and serve the files. This bundle could provide base classes for this tasks.
